version: "3"
services:
  frontend:
    image: ${REGISTRY-127.0.0.1:5000}/hotel_app_frontend_single_node_memdb
    entrypoint: frontend
    container_name: 'hotel_app_frontend'
    ports:
      - "8080:8080"
    restart: always

  profile:
    build:
      context: .
      args:
        - DB=mongodb
    image: hotel_app_profile_single_node_mongodb
    container_name: 'hotel_app_profile'
    entrypoint: profile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-profile
    restart: always

  search:
    image: ${REGISTRY-127.0.0.1:5000}/hotel_app_search_single_node_memdb
    entrypoint: search
    container_name: 'hotel_app_search'
    ports:
      - "8082:8082"
    restart: always

  geo:
    image: ${REGISTRY-127.0.0.1:5000}/hotel_app_geo_single_node_memdb
    container_name: 'hotel_app_geo'
    entrypoint: geo
    ports:
      - "8083:8083"
    restart: always

  rate:
    image: ${REGISTRY-127.0.0.1:5000}/hotel_app_rate_single_node_memdb
    container_name: 'hotel_app_rate'
    entrypoint: rate
    ports:
      - "8084:8084"
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: 'hotel_app_jaeger'
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always

  mongodb-profile:
    image: mongo:4.4.6
    container_name: 'hotel_app_profile_mongo'
    ports:
      - "27018:27017"
    restart: always
    volumes:
      - profile:/data/db

volumes:
  profile: